name: Update status on project board
on:
  project_card:
    types: [created, updated, moved]
jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
    
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_number: 1
          content_id: ${{ github.event.client_payload.command.resource.id }}
          field: Date
          value: ${{ env.CURRENT_DATETIME }}
